# Generated by Django 3.1.2 on 2020-10-10 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import miniboxapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('area_code', models.CharField(blank=True, max_length=3)),
                ('local_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('description', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('permissions', models.ManyToManyField(to='miniboxapi.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[miniboxapi.models.validate_cpf])),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miniboxapi.phonenumber')),
                ('roles', models.ManyToManyField(to='miniboxapi.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=4096)),
                ('is_directory', models.BooleanField()),
                ('permissions', models.ManyToManyField(to='miniboxapi.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False, validators=[miniboxapi.models.validate_cnpj])),
                ('trade_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miniboxapi.phonenumber')),
                ('roles', models.ManyToManyField(to='miniboxapi.Role')),
            ],
        ),
    ]
