# Generated by Django 3.1.2 on 2020-10-14 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('miniboxapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilepermission',
            name='file_permission',
        ),
        migrations.AddField(
            model_name='userfilepermission',
            name='permission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FilePermission',
        ),
    ]
