# Generated by Django 3.1.2 on 2020-10-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniboxapi', '0002_file_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
